config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :pages
  resources :groups do
    post 'join_group', to: 'groups#join_group'
    post 'draw', to: 'groups#draw'
    post 'send_receiver', to: 'groups#send_receiver'
    post 'undo_draw', to: 'groups#undo_draw'
  end
  post 'approve_request', to: 'groups#approve_request'
  post 'decline_request', to: 'groups#decline_request'
  post 'white_label_user', to: 'groups#white_label_user'


  devise_for :users
  get 'legal', to: 'pages#legal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
  mount_uploader :photo, PhotoUploader
end

app/models/participant.rb
class Participant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, PhotoUploader
  # belongs_to :group
  has_one :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
  # devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :first_name, :last_name, :avatar) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def join_group
    @user = current_user
    @group = Group.find(params[:group_id])
    @group.save
    @user.group_id = @group.id
    @user.user_status = 'pending'
    if @user.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def approve_request
    @group = Group.find(params[:group_id])
    requesting_user = User.find(params[:user_id])
    requesting_user.user_status = 'approved'
    if requesting_user.save
      mail = UserMailer.with(user: requesting_user).approval_confirmation
      mail.deliver_now
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def decline_request
    @group = Group.find(params[:group_id])
    requesting_user = User.find(params[:user_id])
    requesting_user.user_status = 'declined'
    requesting_user.group_id = nil
    if requesting_user.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def white_label_user
    @group = Group.find(params[:group_id])
    requesting_user = User.find(params[:user_id])
    requesting_user.user_status = 'created'
    if requesting_user.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def draw
    @group = Group.find(params[:group_id])
    @participants = @group.users
    @group_arr = []
    @participants.each do |participant|
      @group_arr << participant if participant.user_status == 'approved'
    end
    @group_arr.shuffle!
    @group_arr.each_with_index do |person, index|
      person.receiver_id = @group_arr[index - 1].id
      person.save
    end
    @group.status = "drawn"
    @group.save
    redirect_to group_path(@group)
  end

  def undo_draw
    @group = Group.find(params[:group_id])
    @participants = @group.users
    @participants.each do |user|
      user.receiver_id = nil
      user.save
    end
    @group.status = 'created'
    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def send_receiver
    @group = Group.find(params[:group_id])
    @participants = @group.users
    @participants.each do |person|
      if person.user_status == 'approved' && @group.status == 'drawn'
        mail = UserMailer.with(user: person).draw_confirmation
        mail.deliver_now
      end
    end
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @user = current_user
    @group = Group.new
  end

  def create
    @user = current_user
    @group = Group.new(group_params)
    @group.status = 'created'
    if @group.save
      @user.group_id = @group.id
      @user.admin = true
      @user.user_status = 'approved'
      @user.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :user, :photo, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
  end

  def legal
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
 before_action :set_user

  def show
    @groups = Group.where(user: current_user)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to my_account_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_group_members(group)
    @all_members = []
    group.users.map do |user|
      @all_members << user
    end
  end

  def pending(group)
    @pending = []
    group.users.each do |user|
      if user.user_status == 'pending'
        @pending << user
      end
    end
  end

  def approved(group)
    @approved = []
    group.users.each do |user|
      if user.user_status == 'approved'
        @approved << user
      end
    end
  end

  def avatar(user)
    if user.avatar.file.nil?
      image_path("placeholder.jpg")
    else
      user.avatar.url
    end
  end

  def group_admin?(group)
    if current_user.group_id == group.id && current_user.admin == true
      true
    end
  end

  def users_admin(user)
    group = Group.find(user.group_id)
    group.users.each do |user|
      if user.admin == true
        user = @admin
      end
    end
    @admin
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def draw
    @group = Group.find(params[:group_id])
    @participants = @group.users
    @group_arr = []
    @participants.each do |participant|
      @group_arr << participant
    end
    @group_arr.shuffle!
    @group_arr.each_with_index do |person, index|
      person.receiver_id = group_one_arr[index - 1].id
      person.save
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/groups/_banner_image.html.erb
<% if @group.photo.file.nil? %>
  <% cover_img = "#{asset_path('group-bg.jpg')}" %>
<% else %>
  <% cover_img = "#{cl_image_path @group.photo}" %>
<% end %>

<div class="group-bg" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= cover_img %> )">
  <%= link_to 'Back to home', root_path, class: 'btn btn-outline-secondary btn-sm back-button', style:"margin-bottom: 30px" %>
  <div class="group-title">
    <%= @group.name %>
  </div>
</div>

app/views/groups/_greeting.html.erb
 <div class="group-box">

    <div style="margin: 30px 0px">
      <strong>Group status: </strong><%= @group.status %>
    </div>

   <% if current_user.avatar.file.nil? %>
     <img class="avatar" src=<%= asset_path("placeholder.jpg") %>>
   <% else %>
     <%= cl_image_tag current_user.avatar, class: "avatar" %>
   <% end %>

   <h2 style="margin-top: 30px;">Hi, <%= current_user.first_name %></h2>

   <% if current_user.group_id != @group.id && current_user.user_status != 'declined' && @group.status == "created" %>
     <p>Currently, you are not part of this group</p>
     <p>You can request access to the group pushing the button. Once the admin approves it, you are part of it.</p>
     <%= link_to 'Join group', group_join_group_path(@group), method: :post, class: 'btn btn-secondary mb-2' %>
   <% end %>

   <% if current_user.group_id == @group.id && current_user.user_status == "pending" %>
   <p>You have requested access to the group. Your group admin will give you access soon.</p>
   <% end %>

   <% if current_user.user_status == "declined" %>
     <p>You have been declined to join a group. You can white label yourself and try to join another group.</p>
     <%= link_to 'White label me', white_label_user_path(group_id: @group.id, user_id: current_user.id), method: :post %>
   <% end %>

  <% if current_user.group_id == @group.id && @group.status == "created" %>
    <p>Welcome to <%= @group.name %>. Currently, there are being more people invited to this group. Check back once your group admin conducted the drawing to see your receiver.</p>
    <% elsif current_user.group_id == @group.id && @group.status == "drawn" %>
    <p>Your group status changed to "drawn". Scroll down to see to whom you have to give presents to.</p>
  <% end %>

   <% if current_user.group_id == @group.id && current_user.admin == true && @group.status == "created"%>
     <p>You are admin of the group. You have to approve all the people in your group. Only when people are approved, they are part of the game.</p>
     <p>Once all your group members are in the group, click the "draw" button.</p>
     <%= link_to 'Draw now', group_draw_path(@group), method: :post, class: 'btn btn-secondary mb-2' %>

     <% elsif current_user.group_id == @group.id && current_user.admin == true && @group.status == "drawn" %>
      <p>Let your group members know they should login to the group page to see their receiver</br>
      <%= link_to '💌 Send members an email with their receiver', group_send_receiver_path(@group), method: :post, data: {confirm: "Do you really want to send an email?"} %>
      </p>

      <p>You have already conducted a drawing. You shouldn't draw again. If you want to undraw and draw again, click on the link. Make sure to update your group members about it.</br>
      <%= link_to '🚨 Undo draw', group_undo_draw_path(@group), method: :post, data: {confirm: "Do you really want to undraw?"} %>
      </p>

   <% end %>
</div>

app/views/groups/_group_members.html.erb
<div class="group-box">
  <% pending(@group) %>
  <% unless @pending == [] %>
  <h3>Pending requests</h3>
  <p>You need to approve them before they are part of the group</p>
  <% @pending.each do |user| %>
    <div class="card-user">
      <img src=<%= avatar(user) %> >
      <div class="card-user-infos">
        <h2><%= user.first_name %> <%= user.last_name %></h2>
        <p><%= user.user_status %></p>
        <% if user.admin == true %>
          <p>ADMIN</p>
        <% end %>
      </div>
      <% if user.user_status == 'pending' && current_user.admin == true %>
        <div class="card-user-action">
          <% unless @group.status == 'drawn' %>
          <%= link_to 'Approve User', approve_request_path(group_id: @group.id, user_id: user.id), method: :post, class: 'btn btn-secondary mb-2' %>
          <%= link_to 'or decline request', decline_request_path(group_id: @group.id, user_id: user.id), method: :post %>
          <% end %>


        </div>
      <% end %>
    </div>
  <% end %>
  <% end %>


  <% approved(@group) %>
  <div class="approved-box" style="margin-top:30px">
  <h3>Group members</h3>

  <% @approved.each do |user| %>
    <div class="card-user">
      <img src=<%= avatar(user) %> >
      <div class="card-user-infos">
        <h2><%= user.first_name %> <%= user.last_name %></h2>
         <p> <strong>Status: </strong><%= user.user_status %></p>
         <% if user.receiver_id != nil %>
           <p>User has a receiver</p>
         <% else %>
           <p>User doesn't have a receiver</p>
         <% end %>
         <% if user.admin == true %>
           <p>ADMIN</p>
         <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/groups/index.html.erb
<% if current_user.email == 'allmoslechner@gmail.com' %>

<ul>
  <% @groups.each do |group| %>
  <li><%= link_to(group.name, group_path(group)) %></li>
<% end %>
</ul>

<% elsif %>
<p>Only the website admin allmoslechner@gmail.com has access to this page.</p>

<% end %>

app/views/groups/new.html.erb
<div class="container-fluid d-flex justify-content-center group-container">
  <div class="col-lg-6 col-sm-12 col-xs-12 add-group-info">
    <div class="image">
      <img src=<%= asset_path('lama2.png') %>>
    </div>
    <p>Create a secret santa group. Once created, you will be able to invite your friends, family & colleagues</p>
    <% if @user.group_id == nil %>
      <%= simple_form_for @group do |f| %>
        <%= f.input :name, required: true %>
        <%= f.input :description, required: true %>
        <%= f.input :photo, hint: 'This photo will appear as a cover image on your group page.' %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: 'btn btn-secondary mb-2' %>
      <% end %>
    <% else %>
    <p>You are already in a group mister.</p>
    <%= link_to 'Back to home', root_path, class: 'btn btn-outline-secondary btn-sm' %>
    <%= link_to 'Go to my group', group_path(@user.group_id), class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="show-group-container">
  <%= render 'banner_image' %>

    <div class="container group-background">
      <div class="row group-row d-flex justify-content-around align-items-start">

        <div class="col-lg-7 col-sm-12">

          <%= render 'greeting' %>

          <div class="description group-box">
            <input class="form-control form-control-lg" type="text" value="<%= request.original_url %>" id="url-input">
            <button class="btn btn-secondary" id="copy-button">Copy URL</button>
            <p>Copy this URL and invite your friends, family or colleagues to <%= @group.name %></p>
          </div>

          <% if current_user.group_id == @group.id && current_user.user_status == 'approved' %>

          <div class="description group-box">
           <h2>Description & group rules</h2>
           <%= @group.description %>
          </div>

        </div>

        <div class="col-lg-5 col-sm-12">

          <% if @group.status == 'drawn' %>

          <% if current_user.receiver_id != nil %>

          <div class="group-box">
            <% receiver = User.find(current_user.receiver_id) %>
              <h2>You have to give a gift to <%= receiver.first_name %> <%= receiver.last_name %></h2>
              <div class="card-user">
                <% if receiver.avatar.file.nil? %>
                  <img src=<%= asset_path("placeholder.jpg") %>>
                <% else %>
                  <%= cl_image_tag receiver.avatar, class: "avatar" %>
                <% end %>
                <div class="card-user-infos">
                  <h2><%= User.find(current_user.receiver_id).first_name %> <%= User.find(current_user.receiver_id).last_name %></h2>
                  <% if User.find(current_user.receiver_id).admin == true %>
                    <p>ADMIN</p>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
            <% end %>

          <%= render 'group_members' %>

        </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Cookie banner -->
    <script>
      !(function(p,r,i,v,a,c,y){p['MetomicObject']=a;p[a]=p[a]||function(){
      (p[a].q=p[a].q||[]).push(arguments)},p[a].l=1*new Date();c=r.createElement(i),
      y=r.getElementsByTagName(i)[0];c.async=1;c.src=v+'?d='+r.location.host;y.parentNode.insertBefore(c,y)
      })(window, document, 'script', 'https://consent-manager.metomic.io/embed.js', 'Metomic');
      Metomic('load', { projectId: 'prj:55250f2e-46c0-41e2-b50e-8144f44cb37c' });
    </script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-81425830-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-81425830-2');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta property="og:title" content="Holy Moly | the digital secret santa tool" />
    <meta property="og:description" content="Play secret santa with your friends, family or colleagues digitally." />
    <meta property="og:image" content="<%= asset_path('soholymoly.jpg') %>" />



    <title>So holy moly. Your secret santa app.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="nav-box">
      <%= render 'shared/flashes' %>
    </div>

    <div class="main">
      <%= yield %>

    <div class="footer">
      Built with ❤️ by <a href="https://www.linkedin.com/in/allmoslechner/" target="_blank"> &nbsp;Oliver Allmoslechner</a>. With great support from <a href="https://www.linkedin.com/in/sharonmoriel/" target="_blank">&nbsp;Sharon Moriel</a>. <a href="javascript:window.Metomic('ConsentManager:show')">Manage cookies</a> or <a href="<%= legal_path %>">Legal stuff</a>

    </div>

    </div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/_show-user-cards.html.erb
_show-user-cards.html.erb

app/views/pages/home.html.erb
<video autoplay muted loop id="myVideo">
<source src=<%= asset_path('bg.mp4') %> type=video/mp4>
</video>

<div class="column">
  <div class="CTA-box col-sm-12 col-md-6">
    <img src=<%= asset_path('lama.png') %>>
    <div class="heading">
      <h1>The only secret santa tool you'll ever need.</h1>
    </div>
    <div class="CTA">
    <%= link_to 'Create a group', new_group_path, class: 'btn btn-secondary btn-l' %>

    <% if user_signed_in? == false %>
    <p class="login-cta"><%= link_to 'Or log in to view your group', user_session_path %></p>
    </div>
    <% end %>

    <div class="home-action">
    <% if user_signed_in? && current_user.group_id != nil %>
      <%= link_to 'Go to my group', group_path(current_user.group_id), class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to 'logout', destroy_user_session_path, :method => :delete, class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#exampleModal" style="margin-top: 30px;">
      What the fork is secret santa?
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Holy moly. What a tool 🎅</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <h3>About this tool</h3>
            Holy moly allows you to create a group, invite your peers with a unique link and conduct a secret drawing.</br>
            Once the group admin conducts the drawing, every participant sees whom he/she has to give a gift to.</br>
            At the moment, you can only be part of one group with one e-mail address.</br></br>
            Currently, the e-mail function does not work yet. So once the group is drawn, all participants have to check back to the group link in order to see whom she/he has to give a gift to.</br></br>

            <h3>About secret santa</h3>
            Secret santa is a game, usually played during the christmas time amongst friends, family or colleagues.
            The concept is quite simple. Every participant secretly draws a name of another participant.
            The secret santa (the giver) then needs to give one or multiple gifts to his/her receiver.
            Depending on the group, you can define own rules (number of gifts, value per gift, etc.).
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            <%= link_to 'Create a group', new_group_path, class: 'btn btn-secondary btn-l' %>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/pages/legal.html.erb
<div class="container"><h1>Privacy Policy for www.soholymoly.com</h1>

<p>At So holy moly, accessible from https://www.soholymoly.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by So holy moly and how we use it.</p>

<p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

<h2>General Data Protection Regulation (GDPR)</h2>
<p>We are a Data Controller of your information.</p>

<p>www.soholymoly.com legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Information we collect and the specific context in which we collect the information:</p>
<ul>
    <li>www.soholymoly.com needs to perform a contract with you</li>
    <li>You have given www.soholymoly.com permission to do so</li>
    <li>Processing your personal information is in www.soholymoly.com legitimate interests</li>
    <li>www.soholymoly.com needs to comply with the law</li>
</ul>

<p>www.soholymoly.com will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies. Our Privacy Policy was generated with the help of <a href="https://www.gdprprivacynotice.com/">GDPR Privacy Policy Generator</a> and the <a href="https://www.privacypolicygenerator.org">Privacy Policy Generator</a>.</p>

<p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. If you wish to be informed what Personal Information we hold about you and if you want it to be removed from our systems, please contact us.</p>
<p>In certain circumstances, you have the following data protection rights:</p>
<ul>
    <li>The right to access, update or to delete the information we have on you.</li>
    <li>The right of rectification.</li>
    <li>The right to object.</li>
    <li>The right of restriction.</li>
    <li>The right to data portability</li>
    <li>The right to withdraw consent</li>
</ul>

<h2>Log Files</h2>

<p>So holy moly follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

<h2>Cookies and Web Beacons</h2>

<p>Like any other website, So holy moly uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>



<h2>Privacy Policies</h2>

<P>You may consult this list to find the Privacy Policy for each of the advertising partners of So holy moly.</p>

<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on So holy moly, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>

<p>Note that So holy moly has no access to or control over these cookies that are used by third-party advertisers.</p>

<h2>Third Party Privacy Policies</h2>

<p>So holy moly's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You may find a complete list of these Privacy Policies and their links here: Privacy Policy Links.</p>

<p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. What Are Cookies?</p>

<h2>Children's Information</h2>

<p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>

<p>So holy moly does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>

<h2>Online Privacy Policy Only</h2>

<p>Our Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in So holy moly. This policy is not applicable to any information collected offline or via channels other than this website.</p>

<h2>Consent</h2>

<p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_result_html.erb
<% unless user.receiver_id.nil? || @group.status == 'created' %>
<p>gave gifts to <%= User.find(user.receiver_id).first_name %> <%= User.find(user.receiver_id).last_name %></p>
<% end %>